### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [hughperkins/DeepCL#1]
[Extra null pointer checks are not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") like the following.
* [ConvolutionalLayer](https://github.com/hughperkins/DeepCL/blob/7d2f8f809db3444398e4096e7c1050d072b11840/src/ConvolutionalLayer.cpp#L69 "Destructor for ConvolutionalLayer")
* [MultiNet](https://github.com/hughperkins/DeepCL/blob/e4a41c63b4d6ac8b685e2a8eec789727d58bb42a/src/MultiNet.cpp#L40 "Destructor for MultiNet")
* [PropagateAuto](https://github.com/hughperkins/DeepCL/blob/e5def1c588f2a5207032cc3071f28dff113d3833/src/PropagateAuto.cpp#L53 "Destructor for PropagateAuto")

**Comment by hughperkins** [comment]
Hi Markus,

Ok, you're saying that if the pointer is incorrectly non-zero, then the if check for zero wont prevent the program crashing, and if it is zero, then the delete will work anyway?

Ok, sounds reasonable.  If you submit a Pull Request for this, I will accept it.

Hugh

**Comment by hughperkins** [comment]
Hi.  I guess this 'issue' is mostly  to try to get publicity for your 'elfring' project, rather than because you actually want to fix this, is that right? :-P

I'm going to close this issue, because I quite like the null checks actually.  But if you submit a pull request for this, I will accept it :-)
