### ISSUE TITLE
why faileded to open file: ../data/cifar10/train-dat.mat

### ISSUE THREAD

**Issue by gjcjdghks** [hughperkins/DeepCL#114]
first, i made dataset (test-dat.mat, test-cat.mat, train-cat.mat, train-dat.mat ) using cifar-to-mat ./data/cifar (this is commandline).
and i input           ~/DeepCL$ deepcl_train dataset=cifar10 datadir=./data/cifar10
BUT! failed to open file... what`s the matter?????

**Comment by Barrett17** [comment]
The deepcl_train seems to ignore the datadir argument. So basically it looks always in "../data/cifar10".

To fix your problem do it this way (linux) : 

* Copy the cifar10-batches-bin directory as data/cifar10

`cp cifar-10-batches-bin data/cifar10 -R`

* Be sure to be in the build folder and run `deepcl-train dataset=cifar10`

The program will look for "../data" that's why you need to be into build (or in a subdirectory), hope that helps.

**Comment by Barrett17** [comment]
@hughperkins what about inverting the custom parameters order with the presets in train.cpp so that custom variables can be overridden?

**Comment by hughperkins** [comment]
Sure, sounds good :-) . PR welcome.  Preferably with a unit-test, so it's easy for me to check :-)

**Comment by Barrett17** [comment]
Ok, I'll look at it in the next days :)
