### ISSUE TITLE
Documentation for C++ API

### ISSUE THREAD

**Issue by akashsachdeva** [hughperkins/DeepCL#95]
Hi,

I  have recently started working with CNN and also using this library(and its really good), so correct me if I am wrong somewhere. 

In the documentation for C++ API mentioned here (https://github.com/hughperkins/DeepCL/blob/master/doc/NeuralNetAPI.md), I guess there are some changes in train and test part . 

_NetLearner netLearner( trainer, net,Ntrain, trainData, trainLabels,Ntest, testData, testLabels );
  netLearner.setSchedule( numEpochs );
 
 netLearner.setBatchSize( batchSize );                
 netLearner.learn();_                                          

The last two i.e. setBatchSize and learn argument is not available anymore.

Also for Test
_BatchLearner batchLearner( net );
int testNumRight = batchLearner.test( batchSize, Ntest, testData, testLabels );_

I guess BatchLearner class is also not available anymore!!! 

Can you please let me know the testing class... 
I am currently getting familiar with DeepCl (later to use in my uni project) and for that trying Lenet5. To test can you please suggest anything?

Thank You for your help!

**Comment by hughperkins** [comment]
The unit tests are pretty definitive; they all pass, ie take a look in https://github.com/hughperkins/deepcl/tree/master/test eg https://github.com/hughperkins/DeepCL/blob/master/test/testsimpleconvolvenet.cpp

Otherwise, there is doxygen documentation.  I might need to regenerate it.  The docs are at http://deepcl.hughperkins.com/4.x.x/html/annotated.html  Seems like a really old version though. Perhaps I should regenerate it...

**Comment by hughperkins** [comment]
Updated the doxygen docs: http://deepcl.hughperkins.com/doxygen/annotated.html

**Comment by hughperkins** [comment]
(added notes on running doxy at https://github.com/hughperkins/DeepCL/blob/master/doc/doxy/Doxyfile )

**Comment by akashsachdeva** [comment]
Thanks for the help..! I'll go through it.

**Comment by hughperkins** [comment]
k :-)  Let me know if you have any questions/comments please.
