### ISSUE TITLE
DeepCL fpr Altera FPGA 

### ISSUE THREAD

**Issue by mohmsslk** [hughperkins/DeepCL#98]
Hello, 

I want to install DeepCL for Altera FPGA, I installed OpenCL SDK for Altera but when I run "deepcl_unittests" it can't detacte it, even my GPU AMD, it just detecte my CPU intel, any idea how to install DeepCL for Altera FPGA?
I'm using windows.

**Comment by marty1885** [comment]
As what I cone to know (At least this is what happens in my lab). Altera OpenCL SDK seems to not support OpenCL ICD. Which is required for multiple platform to co-exist.
By default, OpenCL finds platforms that support ICD. But since Altera's SDK don't support ICD. The default OpenCL library won't find it. You need to directly link your executable to Altera OpenCL SDK's OpenCL.dll to use the FPGA as a OpenCL device.

**Comment by viper7882** [comment]
Hi @marty1885 ,

According to the latest [Intel FPGA Open CL] (https://www.altera.com/content/dam/altera-www/global/en_US/pdfs/literature/hb/opencl-sdk/aocl_programming_guide.pdf), **The Intel FPGA SDK for OpenCL supports the OpenCL ICD extension from the Khronos Group**.

Chances are you will have to install Quartus v17.0 to enable OpenCL ICD in Intel FPGA.
